---
title: "Configurable clinical data harmonization with help from LLMs"
author: "Leslie Emery"
institute: "Informatics & Predictive Sciences | Bristol Myers Squibb"
format:
  revealjs:
    theme: [simple, bms-reveal.scss]
    logo: assets/bms-logo.png
    slide-number: true
    width: 1280
    height: 720
    incremental: false
    include-in-header: title-logo.html
    title-slide-attributes:
      data-background-gradient: "linear-gradient(135deg, #BE2BBB 0%, #8f1f8d 100%)"
---

## Clinical data harmonization project description

- bullet 1
    - sub 1
    - sub 2
        - sub sub 1
- bullet 2
- [Link text](bms.com)

::: {.notes}
Clinical data harmonization project description

- Patients, often at most difficult time in their lives, undergo extensive sometimes painful procedures, spend precious hours having data collected
- Important to find as many insights from data as possible, beyond just the original clinical trial objective
:::

## Big picture description of a data harmonization project (e.g. 10 studies) and how much work goes into it

::: {.notes}
Big picture description of a data harmonization project (e.g. 10 studies) and how much work goes into it

- Diagram here of the many files from many studies, custom code for each input file to output transformation, lots of variation in the code, lots of repeating the same kinds of things over an over again
:::

## Big picture description of a data harmonization project using config files made by LLM with human review

::: {.notes}
Big picture description of a data harmonization project using config files made by LLM with human review

- Simpler diagram here of agent workflow
- "I'm going to tell you about how I went from this [complicated diagram] to this [simple diagram]"
:::

## I built out this workflow based on my deep expertise in data harmonization

::: {.notes}
I built out this workflow based on my deep expertise in data harmonization

- match input columns to desired output columns
- figure out what format it's in
- convert it to the format you want it to be
- Overview of some example data from 3 studies (real column names, but not real data)
:::

## Data model (output)


```yaml
unique_subject_id:
  key: true
  data_type: character
  inputs:
      USUBJID
  terms:
    loinc: 97851-0
    CDISC: 555555555
    whodrug: 44444444
    rxnorm: 33333333
    snomed: xxxxxxxx
    icd10: 8888888
    MedDRA: xxxxxxxx
subject_id:
  key: false  # assume false by default
  data_type: character
  inputs:
    SUBJID
```

::: {.notes}
Data model (output)

- Show prompt to get Posit Assistant to make the data model based on a group of studies
- Show example data model
    - Structure:
        - _structure.yaml file; domain.yaml for each domain included
    - Domains: adverse_events, exposure, subjects, lab_tests, time_to_event, response
:::

## Harmonization configs (input)

::: {.notes}
Harmonization configs (input)

- Show example from subjects domain for 3 different studies
- For each desired output column:
    - Which dataset & column to get it from
    - What data type is it
    - What units is it already in
    - What categorical values exist
- Mention relation to data dictionary? (of recent interest in field)
- Side story here about me telling Eslam to start with dm file, but it turned out to be most difficult
:::

## Config-based harmonization code

```r
derive_subject_level <- function(data_files_read){
  
  # Get the set of columns to be included in the output
  domain_spec <- read_daap_specification("subject_level")
  
  # Get the harmonization config
  domain_config <- read_harmonization_config("subject_level")
  domain_config_df <- harmonization_config_to_tibble(domain_config)
  
  # Which columns need to be in the output?
  expected_keys <- purrr::map_chr(domain_spec$keys, .f=names)
  expected_keys_and_columns <- c(expected_keys,
                                 purrr::map_chr(domain_spec$columns, .f=names))
  
  # Use the harmonization config to find the source data for each column
  domain_config_df <- domain_config_df %>% 
    mutate(
      # TODO: make this more general in case there are >2 files that map to the domain
      preferred_file = case_when(
        "adsl" %in% file ~ "adsl",
        TRUE ~ first(file)
        ),
        .by=output_column
    )
  
  # Get the mapped columns from each source file
  get_mapped_data <- function(source_file){  # source_file <- "dm"
    # TODO: make this more general for more than just adam/sdtm input types
    input_type <- ifelse(source_file %in% names(data_files_read$adam), "adam", "sdtm")
    source <- data_files_read[[input_type]][[source_file]](config=config)
    source_map <- domain_config_df %>%
      filter((preferred_file == source_file | output_column %in% expected_keys ) &
               file == source_file)
    rename_map <- source_map$column
    names(rename_map) <- source_map$output_column
    mapped_data <- source %>% 
      select(all_of(source_map$column)) %>% 
      rename(all_of(rename_map))
  }
  subject_level <- purrr::map(unique(domain_config_df$preferred_file), .f=get_mapped_data)
  subject_level <- purrr::reduce(subject_level, .f=full_join)   # running this for each split of response

  # TODO: add a check that every col from expected_keys_and_columns is in output
  # and no unexpected columns

  return(subject_level)
}
```

::: {.notes}
Config-based harmonization code

- Show code snippets from subjects domain
- Fully working for simple case of just renaming columns and converting data types
- Still to handle (should I mention this or not?):
    - Converting units
    - Harmonizing categorical values
:::

## The harmonization config files maximize human attention/time spent reviewing LLM output

::: {.notes}
The harmonization config files maximize human attention/time spent reviewing LLM output

- The configs capture the most important parts of the harmonization decisions -- which inputs map to which outputs, and what data transformations happen
- Screenshot of the review app Burak has built
:::

## You get a great data dictionary for your output basically for free with the harmonization configs + data model

::: {.notes}
You get a great data dictionary for your output basically for free with the harmonization configs + data model

- Clear definition of final output data
- Links back to the input dataset + columns that were used
:::

## We've done this in a pilot project and it gets us pretty close to final state so we can focus our time on the hard parts

::: {.notes}
We've done this in a pilot project and it gets us pretty close to final state so we can focus our time on the hard parts

- Internship, mention Eslam
:::

## We are building out a Claude Code plugin using our daapr framework

::: {.notes}
We are building out a Claude Code plugin using our daapr framework

- Mention Jason for plugin
- Show plugin workflow design
:::

## You can use these approaches for other use cases

::: {.notes}
You can use these approaches for other use cases

- Any project where you're combining data from multiple sources (e.g. COVID data from different health authorities, published datasets from different reserach groups, eCommerce data from acquired companies, etc.)
- Use data model .yaml to instruct LLM to make the output format you want
- Use a config file that describes all of your inputs (makes it easier for LLM to reason about your data)
:::
