treeView-beta
📁 data-model/  ## Repo on GitHub
    🌳 _data_structure.yaml  :::highlight  ## Definition of output (list of data frames)
    ⚠️ adverse_events.yaml
    💊 concomitant_medications.yaml
    💉 exposure.yaml
    🏥 hospitalization.yaml
    🧪 lab_tests.yaml  ## Common definition for all lab_test data frames
    🧪 lab_test_codes.yaml  ## Definition of each lab test name & code
    📈 response.yaml
    📈 response_params.yaml
    👤 subject_level.yaml
    📅 subject_visit.yaml
    ⏳ time_to_event.yaml
    ⏳ time_to_event_params.yaml
