%%{init: {'themeCSS': '.treeView-node-description { fill: #4F4A4A; }'}}%%
treeView-beta
📁 data-model/
    ⚠️ adverse_events.yaml
    👤 demographics.yaml
    🏥 hospitalization.yaml
    🧪 lab_tests.yaml
    💊 medications.yaml
    📈 response.yaml
    ⏳ time_to_event.yaml
    💉 treatment.yaml
    📅 visits.yaml
