%%{init: {'themeCSS': '.treeView-node-description { fill: #4F4A4A; }'}}%%
treeView-beta
📁 data-model/  ## Repo on GitHub
    ⚠️ adverse_events.yaml
    🏥 hospitalization.yaml
    🧪 lab_tests.yaml  ## Common definition for all lab_test data frames
    🧪 lab_test_codes.yaml  ## Definition of each lab test name & code
    💊 medications.yaml
    📈 response.yaml
    📈 response_params.yaml
    👤 subject_level.yaml
    📅 subject_visit.yaml
    ⏳ time_to_event.yaml
    ⏳ time_to_event_params.yaml
    💉 treatment.yaml
